services:
  - type: web
    name: my_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_project.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
